config/routes.rb
Rails.application.routes.draw do
  # resources :dogs, only: [:index, :new, :create, :show, :edit, :update]

  resources :dogs
  root 'dogs#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to dogs_url, notice: "Successfully Saved"
    else
      flash.now[:notice] = "Something went wrong, and we couldn't save your dog."
      render :new
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    if @dog.update(dog_params)
      redirect_to dogs_url, notice: "Successfully Saved"
    else
      flash.now[:notice] = "Something went wrong, and we couldn't update #{@dog.name}."
      render :edit
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    if @dog.destroy
      redirect_to dogs_url, notice: "Successfully Deleted"
    else
      redirect_to dogs_url, notice: "Could not delete #{@dog.name}"
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age, :breed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for @dog do |dog_fields| %>
  <%= dog_fields.label :name %>
  <%= dog_fields.text_field :name %>
  <br />
  <%= dog_fields.label :breed %>
  <%= dog_fields.text_field :breed %>
  <br />
  <%= dog_fields.label :age   %>
  <%= dog_fields.number_field :age %>
  <br />
  <%= dog_fields.submit %>
<% end %>

app/views/dogs/edit.html.erb
<h1>Edit a new Dog</h1>

<%= render 'form' %>

app/views/dogs/index.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>
<h1>My Dogs</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Profile</th>
    </tr>
  </thead>
  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.id %></td>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.age %></td>
        <td><%= link_to("Show", dog_path(dog)) %></td>
        <td><%= link_to("Edit", edit_dog_path(dog))%></td>
        <td><%= link_to("Delete", dog, method: :delete, data: { confirm:"Are you sure?" })%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add a New Dog", new_dog_path %>

app/views/dogs/new.html.erb
<h1>Add a new Dog</h1>

<%= render 'form' %>

app/views/dogs/show.html.erb
<!-- Dog's name -->
<h1>Details for: <%= @dog.name %></h1>
<!-- Dog's id -->
<p>
  <strong>ID: <%= @dog.id %></strong>
</p>
<!-- Breed -->
<p>
  <strong>Breed: <%= @dog.breed %></strong>
</p>
<!-- age -->
<p>
  <strong>Age: <%= @dog.age %></strong>
</p>
<!-- date added -->
<p>
  <strong>Date Added: <%= @dog.created_at.stamp("5 Aug 2017") %></strong>
</p>

<%= link_to("The Dogs of X", dogs_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoggieDayCare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>